### ISSUE TITLE
modify the bounding box

### ISSUE THREAD

**Issue by ClintJoey** [FeiGeChuanShu/ncnn-android-yolov8#22]
Thanks for this @FeiGeChuanShu, I managed to make it work. I want to modify the color of the bounding box for each class predicted like for example: person = blue bounding box, car = orange bounding box, tv = red bounding box, etc. Does anyone know how to do this? Thanks in advance (I'm still a newbie).

**Comment by NovaShen555** [comment]
yolo.cpp line373
u can change the rgb number to change the color
