### ISSUE TITLE
模型精度问题

### ISSUE THREAD

**Issue by JIANG3330** [FeiGeChuanShu/ncnn-android-yolov8#5]
飞哥你好，我用工程里的yolov8s模型跑了一下coco val2017的数据集计算AP，发现精度下降得有点多。
```
本工程的yolov8s模型的结果:
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.332
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.416
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.350
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.081
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.291
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.653
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.286
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.340
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.340
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.081
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.299
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.664
```

下面是YOLOV8官方的结果
Model | size(pixels) | mAPval50-95 | SpeedCPU ONNX(ms) | SpeedA100 TensorRT(ms) | params(M) | FLOPs(B)
-- | -- | -- | -- | -- | -- | --
YOLOv8s | 640 | 44.9 | 128.4 | 1.20 | 11.2 | 28.6

您知道这是什么原因吗？精度甚至比yolov5s低。

**Comment by liuguicen** [comment]
这个我也好像遇到了，应该是有什么问题，手机运行直观的和nanodet比较也差很多
飞哥有没有时间看一下原因呀
nanodet plus 目标小一些
![2AB794117DF8DEC41D5DCE3BA95F8B77](https://user-images.githubusercontent.com/13100498/216930960-ce171dd0-479a-4b6f-a3d9-42d1a0e5ebc3.jpg)
yolov8 目标还大一些
![9775A382380172528DF4B7EA4029D40A](https://user-images.githubusercontent.com/13100498/216931025-ca4cc2cc-bd99-4f96-933d-a1be5d56e0bc.jpg)

**Comment by JIANG3330** [comment]
找到问题了， 是input size跟RGB BGR颜色空间问题
