### ISSUE TITLE
convert model to ncnn error

### ISSUE THREAD

**Issue by CNruxiangduan** [FeiGeChuanShu/ncnn-android-yolov8#7]
Hi,
I trained a new model by official yolov8,and i convert pt model to onnx by "yolo export model=path/to/best.pt format=onnx",and use onnx2ncnn generate .param and .bin,but when i replace these files in your code,it can not get right result.and when i use android studio,it can not run.how to solve this issue,thanks.

**Comment by samiechan** [comment]
I did the same thing, but used [pnnx](https://github.com/pnnx/pnnx) for converting. I also trained on 1 class, so I changed yolo.cpp class_names array to have only my trained class and generate_proposals method num_class variable to 1. Next thing I found that the output name is different from what is defined in ex.extract(...) in yolo.cpp by opening my model in netron app. Mine has the output0 as name of the output. Next thing to look at is the input size. In yolov8ncnn it is 320, but yolov8 default size is [640](https://docs.ultralytics.com/cfg/). Mine was trained on 800 img size. But changing these things is not enough. I found that converting yolov8s.torchscript model using pnnx has different output comparing to model is assets folder. I tried to run pnnx yolov8s.pt inputshape=[1,3,800,800] but no success currently.

**Comment by FeiGeChuanShu** [comment]
@CNruxiangduan could you send your onnx to my email

**Comment by FeiGeChuanShu** [comment]
@samiechan sorry about that,i haven't use pnnx to convert this model, i will try it later

**Comment by FeiGeChuanShu** [comment]
@samiechan plz change split in c2f module to slice this method https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/models/common.py#L87-L91

**Comment by samiechan** [comment]
0. Created new conda environment (python 3.8)
1. Cloned the official repo `git clone https://github.com/ultralytics/ultralytics`
2. Changed file as suggested by @FeiGeChuanShu (ultralytics\ultralytics\nn\modules.py)
3. `cd ultralytics`
4. Installed dev environment `pip install -e '.[dev]'`
5. Downloaded my dataset into datasets folder and run `yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=25 imgsz=320 plots=True`
6. Exported my model into onnx format using `yolo export model=path/to/best.pt format=onnx`
7. Downloaded latest ncnn [version](https://github.com/Tencent/ncnn/releases) for Windows VS2022
8. Extracted the ncnn archive and copied my model into `ncnn-20221128-windows-vs2022/x64/bin`
9. In PowerShell run `./onnx2ncnn best.onnx best.param best.bin`
10. Cloned ncnn-android-yolov8 repo
11. Downloaded ncnn-20221128-android-vulkan and opencv-mobile-4.6.0-android.zip, extracted them to the `ncnn-android-yolov8/ncnn-android-yolov8/app/src/main/jni` folder
12. Modified `CMakeLists.txt` file
13. Modified `yolo.cpp` file (`num_class = 1, class_names[] = { "My Class" }, ex.extract("output0", out)`). Output name can be found in .param file.
14. Modified `yolov8ncnn.cpp` `modeltypes[] = { "s" }`
15. Provided ndk.dir in `local.properties` (e.g. `C\:\\Users\\username\\AppData\\Local\\Android\\Sdk\\ndk\\21.3.6528147`)
16. Removed `<item>n</item>` from strings.xml
17. Copied my model (.bin and .param files) to the assets folder and renamed them to yolov8s for simplicity.
18. Opened Android Studio, builded project and run it on my Android device
19. As a result the app crashes and before that I can see a lot of bounding boxes. The error is `Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x71e1cc04c0 in tid 28015 (ImageReader-640), pid 27978 (cent.yolov8ncnn)`

Does it mean that the model conversion was wrong? How to convert custom model and use it with ncnn-android-yolov8 app?
I also tried to convert model using https://convertmodel.com/#input=onnx&output=ncnn but it did not work either.

**Comment by FeiGeChuanShu** [comment]
@CNruxiangduan @samiechan  i have update readme with some changes for v8 code for ncnn model

**Comment by samiechan** [comment]
@FeiGeChuanShu Thank you so much! It works now. Should be noted that these changes should be applied after model is trained and only when you want to export it. Is it somewhere documented to make these changes or you figured it out yourself?
Thank you.

**Comment by ammarasnawi** [comment]
Hi @FeiGeChuanShu , I tried to convert and change the modules block.py and head.py, but when the I try to run it on Android Device, it didn't make any detection.

Below is the code for Class detect @ head.py
`    def forward(self, x):
        """Concatenates and returns predicted bounding boxes and class probabilities."""
        shape = x[0].shape  # BCHW
        for i in range(self.nl):
            x[i] = torch.cat((self.cv2[i](x[i]), self.cv3[i](x[i])), 1)
        if self.training:
            return x
        elif self.dynamic or self.shape != shape:
            self.anchors, self.strides = (x.transpose(0, 1) for x in make_anchors(x, self.stride, 0.5))
            self.shape = shape

        pred = torch.cat([xi.view(shape[0], self.no, -1) for xi in x], 2).permute(0, 2, 1)  
        return pred`

Here is the code for class c2f @ block.py
`class C2f(nn.Module):
    """Faster Implementation of CSP Bottleneck with 2 convolutions."""

    def __init__(self, c1, c2, n=1, shortcut=False, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super().__init__()
        self.c = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, 2 * self.c, 1, 1)
        self.cv2 = Conv((2 + n) * self.c, c2, 1)  # optional act=FReLU(c2)
        self.m = nn.ModuleList(Bottleneck(self.c, self.c, shortcut, g, k=((3, 3), (3, 3)), e=1.0) for _ in range(n))

    def forward(self, x):
        # """Forward pass through C2f layer."""
        # y = list(self.cv1(x).chunk(2, 1))
        # y.extend(m(y[-1]) for m in self.m)
        # return self.cv2(torch.cat(y, 1))

#         print("ook")
        x = self.cv1(x)
        x = [x, x[:, self.c:, ...]]
        x.extend(m(x[-1]) for m in self.m)
        x.pop(1)
        return self.cv2(torch.cat(x, 1))

    def forward_split(self, x):
        """Forward pass using split() instead of chunk()."""
#         y = list(self.cv1(x).split((self.c, self.c), 1))
#         y.extend(m(y[-1]) for m in self.m)
#         return self.cv2(torch.cat(y, 1))
        
        x = self.cv1(x)
        x = [x, x[:, self.c:, ...]]
        x.extend(m(x[-1]) for m in self.m)
        x.pop(1)
        return self.cv2(torch.cat(x, 1))`

Hope to get response from you. Thank you.

**Comment by Yogurt2019** [comment]
https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/36

this might solve your problem.

**Comment by Yogurt2019** [comment]
> I did the same thing, but used [pnnx](https://github.com/pnnx/pnnx) for converting. I also trained on 1 class, so I changed yolo.cpp class_names array to have only my trained class and generate_proposals method num_class variable to 1. Next thing I found that the output name is different from what is defined in ex.extract(...) in yolo.cpp by opening my model in netron app. Mine has the output0 as name of the output. Next thing to look at is the input size. In yolov8ncnn it is 320, but yolov8 default size is [640](https://docs.ultralytics.com/cfg/). Mine was trained on 800 img size. But changing these things is not enough. I found that converting yolov8s.torchscript model using pnnx has different output comparing to model is assets folder. I tried to run pnnx yolov8s.pt inputshape=[1,3,800,800] but no success currently.

https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/36
this might solve your problem.
